name: 构建镜像：s6-overlay
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建镜像：s6-overlay
    env:
      IMAGE_NAME: s6-overlay
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      -
        name: Prepare
        id: prepare
        run: |
          version=$(curl -s https://api.github.com/repos/just-containers/s6-overlay/releases/latest | jq -r .tag_name | sed "s/v//")
          echo ::set-output name=version::${version}

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - 
        name: Set Up Cache
        uses: actions/cache@v2
        id: buildx-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx

      - 
        name: Buildx Latest
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.IMAGE_NAME }}
          file: ${{ env.IMAGE_NAME }}/Dockerfile
          platforms: |
            linux/386
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
            linux/ppc64le
          push: true
          build-args: |
            ALPINE_VERSION=latest
            S6_OVERLAY_VERSION=${{ steps.prepare.outputs.version }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.prepare.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - 
        name: Buildx Bin is Softlink Version
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.IMAGE_NAME }}
          file: ${{ env.IMAGE_NAME }}/Dockerfile.bin_is_softlink
          platforms: |
            linux/386
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
            linux/ppc64le
          push: true
          build-args: |
            ALPINE_VERSION=latest
            S6_OVERLAY_VERSION=${{ steps.prepare.outputs.version }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.prepare.outputs.version }}-bin-is-softlink
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:bin-is-softlink