name: 构建镜像：ubuntu-s6
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建镜像：ubuntu-s6
    env:
      IMAGE_NAME: ubuntu-s6
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - 
        name: Set Up Cache
        uses: actions/cache@v2
        id: buildx-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx

      - 
        name: Buildx Latest
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.IMAGE_NAME }}
          file: ${{ env.IMAGE_NAME }}/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/ppc64le
          push: true
          build-args: |
            UBUNTU_VERSION=latest
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:20.04
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:focal
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
